### ISSUE TITLE
npm install gives version 1.2.6, with a missing (wrong?) git hash. 

### ISSUE THREAD

**Issue by patrickdbakke** [nielsgl/sequelize-paper-trail#13]
Npm install is currently replying with this tarball: 
https://registry.npmjs.org/sequelize-paper-trail/-/sequelize-paper-trail-1.2.6.tgz

This tarball is behind (ahead of?) latest. 

# Steps to reproduce: 
1. Run `npm view sequelize-paper-trail`
2. See that 1.2.6 is the latest published package. This version is tied to some unknown commit hash `13aeff4c02fe9de0586b76d0dbfda0638ce47bb6`. I cannot track down this hash on github. 

This version is behind the latest 1.2.3/1.2.4 on github, and is missing the continuation-local-storage updates. It seems roughly equal to the code at: https://github.com/nielsgl/sequelize-paper-trail/commit/762ae6a9ab593c19ca92464dc3d99dcb0b85bdfe

# Current workaround:
`npm install sequelize-paper-trail@1.2.4`

**Comment by nielsgl** [comment]
Resolved with version 1.3.3 which is both on GitHub and NPM.
@patrickdbakke  if you're still having problems please create a new ticket.
