### ISSUE TITLE
notNull Violation: Revision.documentId cannot be null

### ISSUE THREAD

**Issue by ketus** [nielsgl/sequelize-paper-trail#35]
hi,

First off: great project! Really appreciated.

I'm having a bit of a trouble to get it working, though.
When I update trailed model, sequelize returns:
```Revision save error
{ SequelizeValidationError: notNull Violation: Revision.documentId cannot be null
    at Promise.all.then (..../node_modules/sequelize/lib/instance-validator.js:77:15)
```
I've left options as defaults. My update query runs as expected.
What exactly is purpose of `document` / `documentId` fields?
Should I include `documentId` in query somewhere?

**Comment by ksfreitas** [comment]
@ketus update the libraries (and sequelize) and check if this error persists.

* `document` store all entity data in JSON format, in revision number
* `documentId` is the primary key of the changed entity, utilized with `model` field to track the changes.

**Comment by RsHalit** [comment]
I resolve that issue with putting  `revision.documentId = revision.document._id` in function createAfterHook, before save.

**Comment by nielsgl** [comment]
@RsHalit if it's still a problem with the latest version without that manual change please reopen the issue and I'll look into it.
