### ISSUE TITLE
underscoredAttributes doesn't work

### ISSUE THREAD

**Issue by createthis** [nielsgl/sequelize-paper-trail#47]
```
Revision save error
{ SequelizeValidationError: notNull Violation: Revision.document_id cannot be null
```

You're hard coding the attribute here as `documentId`, I think: https://github.com/nielsgl/sequelize-paper-trail/blob/34d0ef3306d3c24656ca45a7852ce62f05d5ead2/lib/index.js#L313

**Comment by createthis** [comment]
see PR. seems to work on my end.

**Comment by createthis** [comment]
This is closed, but it's been reverted? What happened?

**Comment by nielsgl** [comment]
I'll add it back in but with another pull request it requires some changes to the code. If you can update it I'll be happy to merge it as soon as I can :)

**Comment by createthis** [comment]
@nielsgl updated. Have a look.

**Comment by nielsgl** [comment]
Merged it. I'll close it for now 👍
