### ISSUE TITLE
Add a way to track removed records

### ISSUE THREAD

**Issue by ksfreitas** [nielsgl/sequelize-paper-trail#54]
If a object is destroyed, it's not possible to know when and who did this, assuming `paranoid` mode is off in sequelize.

**Comment by nielsgl** [comment]
Merged and released 🎉

**Comment by createthis** [comment]
need to update the migration example:

```
SQLITE_ERROR: table Revisions has no column named operation
```

**Comment by createthis** [comment]
@nielsgl I've updated the migration example in #57
