### ISSUE TITLE
Requesting changes for a specific query

### ISSUE THREAD

**Issue by ekeuus** [nielsgl/sequelize-paper-trail#62]
Is there a way to request all changes for a specific parameter or can I add additional columns to identify stuff by? I might want to add a group or project id or so.

I was unable to find it out by reading the docs. Thanks!

I went ahead and implemented a version in #63

**Comment by nielsgl** [comment]
Thanks 👍 I'll review it this weekend.

**Comment by ekeuus** [comment]
I'm up for api changes if you have some ideas. I just wanted an extension like this and so far it has been satisfying.

The user id fk option could also be unified with other pr solutions

**Comment by nielsgl** [comment]
I've been working on refactoring some of the code (just released as `3.0.0.rc-4` it's in this branch: https://github.com/nielsgl/sequelize-paper-trail/tree/feature/refactoring if you can update your PR it will be easier to review.

**Comment by nielsgl** [comment]
@ekeuus I added some comments in your PR #63
