### ISSUE TITLE
Paper Trail not tracking Sequelize.DATE type column

### ISSUE THREAD

**Issue by JosielFaleiros** [nielsgl/sequelize-paper-trail#67]
Hi, I have followed the install instructions, and got this awesome lib working on my project, :100:  
but, when I was looking in the revisions table for the data been stored for changes in date columns, I was not able to find any date change tracked by this lib =/ .
Expected behavior: Given a Sequelize model defined with a date column, when some date value of an instance of this model is updated and persisted, the sequelize-paper-trail should track the date value update.
Any help are welcome, Thanks in advance!!

**Comment by nielsgl** [comment]
Hey @JosielFaleiros just released v2.6.0 that resolves this issue.
