### ISSUE TITLE
Crash after update to 2.5.0

### ISSUE THREAD

**Issue by lmorningstar116** [nielsgl/sequelize-paper-trail#73]
Crash after update to 2.5.0

`exports.init = function (sequelize: Sequelize, optionsArg: array): Model {
                                  ^
SyntaxError: Unexpected token :`

**Comment by nielsgl** [comment]
Which node version are you using?

**Comment by lmorningstar116** [comment]
10.15.0

**Comment by nielsgl** [comment]
Thanks, I can reproduce it. I'll work on a fix.

**Comment by lmorningstar116** [comment]
on node 11.10.1 crash too

**Comment by nielsgl** [comment]
Yep, too much syntactic sugar, will add a build step to transpile it with babel

**Comment by nwhitmont** [comment]
Ran into this same error today 3/4

Any updates @nielsgl ?

**Comment by nielsgl** [comment]
@nwhitmont I started working on it this weekend (https://github.com/nielsgl/sequelize-paper-trail/tree/develop) but will take a bit longer than expected so I would use the previous version until then. Hopefully I can get a new version out this week.

**Comment by nwhitmont** [comment]
@nielsgl would it be possible to "un-release" 2.5.0?  

This bug will affect anyone who has `^2.4.2` in their `package.json` and the install of `2.5.0` might be accidental.  At least that's how it happened on my team... during a production deployment!

**Comment by nielsgl** [comment]
Yep it's reverted and released as `2.5.2` on npm
