### ISSUE TITLE
Error: CLS namespace required

### ISSUE THREAD

**Issue by JKHeadley** [nielsgl/sequelize-paper-trail#8]
When I require squelize-paper-trail I'm receiving this error.  Any ideas?

**Comment by int3rnet** [comment]
same my issue , any update ??

CLS namespace required

**Comment by nielsgl** [comment]
I'm going to have a look at it as soon as I can this week.

**Comment by nielsgl** [comment]
@int3rnet @gauravarora @sivailangos it should be fixed with the latest release

**Comment by sivailangos** [comment]
Thanks a lot @nielsgl
